#============================================================================================================
#                                   PLUGIN DISCORD COMMANDDE GHOSTSUSHI | CONFIG
#============================================================================================================
                               ## -------- [ MESSAGE ] ------------

message-discord: "Voici le discord du serveur  : §cdiscord.gg/easyteam
"